## Importa a lib

In [3]:
import numpy as np

## Array Mathematics

### Operações Aritméticas

In [19]:
a = np.array([1,2,3])
b = np.array([2,0,1])
x = np.array([[1,3],[5,3]])
z = np.array([[0,1],[2,0]])

#### Multiplicação Hadamart
Multiplicação de elemente a elemento

In [25]:
a*b


array([2, 0, 3])

In [26]:
x*z

array([[ 0,  3],
       [10,  0]])

#### Dot Product
Multiplicação dos vetores gerando um escalar, quando dim=1 e uma multiplicação de matrizes quando dim=2

In [23]:
np.dot(a,b)


5

In [27]:
np.dot(x,z)

array([[6, 1],
       [6, 5]])

## Comparison